name: CI/CD Hola Mundo App

# Se ejecuta en cada push a main
on:
  push:
    branches:
      - main

jobs:
  docker-build-and-push:
    runs-on: ubuntu-latest
    steps:
      # 1️⃣ Clonar el repositorio
      - name: Checkout repository
        uses: actions/checkout@v3

      # 2️⃣ Iniciar sesión en Docker Hub
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD}}

      # 3️⃣ Construir la imagen Docker
      - name: Build Docker image
        run: docker build -t ${{ secrets.DOCKER_USERNAME }}/hola-mundo-app:1.0 .

      # 4️⃣ Subir la imagen a Docker Hub
      - name: Push Docker image
        run: docker push ${{ secrets.DOCKER_USERNAME }}/hola-mundo-app:1.0

  deploy-to-render:
    runs-on: ubuntu-latest
    needs: docker-build-and-push
    steps:
      # 1️⃣ Clonar el repositorio (opcional, ya se clonó antes)
      - name: Checkout repository
        uses: actions/checkout@v3

      # 2️⃣ Desplegar en Render usando API Key y Service ID ocultos
      - name: Deploy to Render.com
        run: |
          curl -X POST \
          -H "Accept: application/json" \
          -H "Authorization: Bearer ${{ secrets.RENDER_API_KEY }}" \
          https://api.render.com/deploy/${{ secrets.RENDER_SERVICE_ID }}